### ISSUE TITLE
less http.Handler more http.HandleFunc

### ISSUE THREAD

**Issue by tj** [gohttp/app#1]
might be missing something but http.Handler is pretty annoying/lame, supporting both might be nice, both have their place I suppose

**Comment by tarrsalah** [comment]
`Go` is about interfaces and composable code, any `http` library should be built around the `http.Handler` interface, http.HandleFunc is what we use usually to construct `http.Handler` handlers.

**Comment by tj** [comment]
I know, but there's no denying that it's ugly for routing wrapping with http.HandlerFunc all the time. Do you know if there's a technical reason why they chose http.Handler as the defacto instead of http.HandleFunc? It has to be one or the other I suppose but I'm curious what the reasoning was, seems like a function would be more elegant in most cases.

**Comment by tj** [comment]
ps I'll add you to the org if you're interested, just trying to collect things in one spot

**Comment by tarrsalah** [comment]
Yes, I totally agree, it's kinda ugly to write this code over and over.

```
func AddBarHundler(ctx *Context) http.Handler {
    return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
            //
    })
}
```

I believe that  `http.Handler` decouples handling requests from the static type of  the `http.HandlerFunc` function, so we can use any type (`struct`` usually).

**Comment by tarrsalah** [comment]
Yes of course, I'm interested (ps: I'm not an experienced `golang http` guy).
